project:
  type: website

website:
  title: "AHK panic-mode tool kit"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - License.qmd

format:
  html:
    theme: Pulse
    css: styles.css
    toc: true



